import { RobotOutlined } from '@ant-design/icons'
import { ReactNode } from 'react'
import { AgentInfo, ActivityEvent } from './types'

export const ROLE_ICON: Record<string, ReactNode> = {
  planner: <RobotOutlined />,
  coder: <RobotOutlined />,
  researcher: <RobotOutlined />,
  analyst: <RobotOutlined />,
}

export const MOCK_AGENTS: AgentInfo[] = [
  {
    id: 'agent-001',
    name: 'Vulcan-Planner',
    version: '2.4.1',
    status: 'idle',
    role: 'planner',
    roleLabel: '规划者',
    capabilities: ['任务分解', '资源规划', '优先级排序', '依赖分析'],
    tools: ['TaskDecomposer', 'ResourceAllocator', 'DependencyGraph'],
    description: '负责任务拆解、规划和协调多 Agent 工作流，擅长将复杂目标分解为可执行的子任务。',
    tags: ['planner', 'orchestrator', 'builtin'],
    maxConcurrentTasks: 3,
    last_seen: new Date(Date.now() - 30000).toISOString(),
    model: 'claude-3-5-sonnet',
    channel: 'wechat',
    currentTask: undefined,
    uptimeSeconds: 86400,
    tokenUsage: { input: 1245000, output: 890000 },
    trustLevel: 'builtin',
  },
  {
    id: 'agent-002',
    name: 'CodeMaster',
    version: '3.1.0',
    status: 'busy',
    role: 'coder',
    roleLabel: '编码者',
    capabilities: ['代码生成', '代码审查', 'Bug修复', '单元测试', '重构'],
    tools: ['CodeGenerator', 'BugDetector', 'TestRunner', 'RefactorHelper'],
    description: '专业代码开发助手，熟练掌握多种编程语言和框架，提供高质量代码生成和审查服务。',
    tags: ['coder', 'developer', 'builtin'],
    maxConcurrentTasks: 5,
    last_seen: new Date(Date.now() - 5000).toISOString(),
    model: 'claude-3-opus',
    channel: 'telegram',
    currentTask: '实现用户认证模块 - RESTful API 设计',
    uptimeSeconds: 43200,
    tokenUsage: { input: 3450000, output: 2100000 },
    trustLevel: 'builtin',
  },
  {
    id: 'agent-003',
    name: 'ResearchBot',
    version: '1.8.2',
    status: 'streaming',
    role: 'researcher',
    roleLabel: '研究者',
    capabilities: ['信息检索', '文献分析', '数据可视化', '报告生成'],
    tools: ['WebSearch', 'PDFReader', 'DataVisualizer', 'ReportGenerator'],
    description: '智能研究助手，帮助用户快速检索和分析海量信息，生成结构化的研究报告。',
    tags: ['researcher', 'analyst', 'builtin'],
    maxConcurrentTasks: 4,
    last_seen: new Date(Date.now() - 2000).toISOString(),
    model: 'gpt-4o',
    channel: 'discord',
    currentTask: '分析 2024年AI领域最新进展报告',
    uptimeSeconds: 72000,
    tokenUsage: { input: 890000, output: 560000 },
    trustLevel: 'builtin',
  },
  {
    id: 'agent-004',
    name: 'DataAnalyzer',
    version: '2.0.5',
    status: 'idle',
    role: 'analyst',
    roleLabel: '分析师',
    capabilities: ['数据分析', '图表制作', '趋势预测', '异常检测'],
    tools: ['DataProcessor', 'ChartMaker', 'TrendPredictor', 'AnomalyDetector'],
    description: '数据分析和可视化专家，能够处理结构化和非结构化数据，提供深入的洞察和预测。',
    tags: ['analyst', 'data', 'builtin'],
    maxConcurrentTasks: 3,
    last_seen: new Date(Date.now() - 120000).toISOString(),
    model: 'gemini-1-5-pro',
    channel: 'web',
    currentTask: undefined,
    uptimeSeconds: 55000,
    tokenUsage: { input: 670000, output: 430000 },
    trustLevel: 'builtin',
  },
]

export const MOCK_ACTIVITIES: Record<string, ActivityEvent[]> = {
  'agent-001': [{ id: 'act-1', type: 'start', description: 'Agent 已启动', timestamp: new Date(Date.now() - 60000).toISOString() }],
  'agent-002': [{ id: 'act-2', type: 'start', description: 'Agent 已启动', timestamp: new Date(Date.now() - 60000).toISOString() }],
  'agent-003': [{ id: 'act-3', type: 'start', description: 'Agent 已启动', timestamp: new Date(Date.now() - 60000).toISOString() }],
  'agent-004': [{ id: 'act-4', type: 'start', description: 'Agent 已启动', timestamp: new Date(Date.now() - 60000).toISOString() }],
}
