"""
Vulcan Multimodal — Processor Registry & Mock Processors

Capability registry for multimodal modality processors (text-to-image, image-to-text,
text-to-speech, speech-to-text, video) with mock implementations that simulate
processing via async delays and synthetic output.
"""

import asyncio
import uuid
from enum import Enum
from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


# ─── Enums ────────────────────────────────────────────────────────────────────

class ModalityType(str, Enum):
    text_to_image = "text-to-image"
    image_to_text = "image-to-text"
    text_to_speech = "text-to-speech"
    speech_to_text = "speech-to-text"
    video = "video"


class ProcessorStatus(str, Enum):
    available = "available"
    busy = "busy"
    error = "error"
    offline = "offline"


class JobStatus(str, Enum):
    pending = "pending"
    processing = "processing"
    completed = "completed"
    failed = "failed"


# ─── Pydantic Models ──────────────────────────────────────────────────────────

class ProcessorInfo(BaseModel):
    """Metadata about a registered modality processor."""
    name: str
    input_type: ModalityType
    output_type: ModalityType
    status: ProcessorStatus = ProcessorStatus.available
    description: str = ""


class Job(BaseModel):
    """A processing job with full lifecycle tracking."""
    id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    type: str
    input: str
    params: Dict[str, Any] = Field(default_factory=dict)
    status: JobStatus = JobStatus.pending
    result: Optional[Dict[str, Any]] = None
    error: Optional[str] = None
    progress: float = 0.0  # 0.0 – 1.0


class JobResult(BaseModel):
    """Convenience wrapper returned from the /process endpoint."""
    job_id: str
    status: JobStatus


# ─── Mock Processors ──────────────────────────────────────────────────────────

_MOCK_DELAY: Dict[str, float] = {
    "text-to-image": 2.0,
    "image-to-text": 1.5,
    "text-to-speech": 1.0,
    "speech-to-text": 1.5,
    "video": 4.0,
}

_MOCK_OUTPUT: Dict[str, Dict[str, Any]] = {
    "text-to-image": {"url": "mock://generated-image.png", "width": 1024, "height": 1024},
    "image-to-text": {"caption": "A visually striking scene generated by Vulcan", "confidence": 0.92},
    "text-to-speech": {"url": "mock://synthesized-audio.mp3", "duration_s": 3.5},
    "speech-to-text": {"transcript": "Hello from Vulcan multimodal", "confidence": 0.95},
    "video": {"url": "mock://rendered-video.mp4", "duration_s": 10, "resolution": "1080p"},
}


async def _mock_process(job: Job) -> Job:
    """Simulate processing with a delay and synthetic output."""
    proc_type = job.type
    delay = _MOCK_DELAY.get(proc_type, 2.0)
    try:
        # Simulate work
        await asyncio.sleep(delay * 0.6)  # slightly shorter for UX
        job.status = JobStatus.processing
        job.progress = 0.5
        await asyncio.sleep(delay * 0.4)
        job.status = JobStatus.completed
        job.progress = 1.0
        job.result = _MOCK_OUTPUT.get(proc_type, {"output": "done"})
        return job
    except asyncio.CancelledError:
        job.status = JobStatus.failed
        job.error = "Cancelled"
        return job
    except Exception as exc:
        job.status = JobStatus.failed
        job.error = str(exc)
        return job


# ─── Capability Registry ──────────────────────────────────────────────────────

class CapabilityRegistry:
    """Thread-safe registry of available modality processors."""

    def __init__(self) -> None:
        self._processors: Dict[str, ProcessorInfo] = {}

    def register(self, info: ProcessorInfo) -> ProcessorInfo:
        self._processors[info.name] = info
        return info

    def unregister(self, name: str) -> bool:
        return self._processors.pop(name, None) is not None

    def get(self, name: str) -> Optional[ProcessorInfo]:
        return self._processors.get(name)

    def list_all(self) -> list[ProcessorInfo]:
        return list(self._processors.values())

    def find_by_type(self, modality: ModalityType) -> list[ProcessorInfo]:
        return [p for p in self._processors.values() if p.input_type == modality]


# ─── Job Queue / Pipeline ────────────────────────────────────────────────────

class JobQueue:
    """Async processing queue with status tracking."""

    def __init__(self, registry: CapabilityRegistry) -> None:
        self._registry = registry
        self._jobs: Dict[str, Job] = {}
        self._tasks: Dict[str, asyncio.Task] = {}

    # -- public API --

    def list_jobs(self) -> list[Job]:
        return list(self._jobs.values())

    def get_job(self, job_id: str) -> Optional[Job]:
        return self._jobs.get(job_id)

    async def submit(self, job: Job) -> JobResult:
        """Enqueue a job for background processing."""
        self._jobs[job.id] = job
        task = asyncio.create_task(_mock_process(job))
        self._tasks[job.id] = task
        return JobResult(job_id=job.id, status=job.status)

    def cancel(self, job_id: str) -> bool:
        """Cancel a running/pending job."""
        task = self._tasks.get(job_id)
        if task and not task.done():
            task.cancel()
        job = self._jobs.get(job_id)
        if job and job.status in (JobStatus.pending, JobStatus.processing):
            job.status = JobStatus.failed
            job.error = "Cancelled by user"
            return True
        return False
